export const heroSection = {
  title: "Padrón de proveedores",
  description:
    "Encuentra los proveedores del fraccionamiento, ubicando proveedores de confianza.",
};

export const proveedores = [
  {
    id: 1,
    nombre: "Materiales ConstruMax",
    telefono: "555-123-4567",
    direccion: "Av. Constructores 123, Ciudad Fraccionamiento",
    correo: "contacto@construMax.com",
    tipoMaterial: "Materiales de construcción",
    tiempoEntrega: "24-48 horas",
    calificacion: 4.8,
    contacto: "Ing. Roberto Martínez",
  },
  {
    id: 2,
    nombre: "Tuberías y Conexiones HidroPlus",
    telefono: "555-234-5678",
    direccion: "Calle Fontana 456, Zona Industrial",
    correo: "ventas@hidroplus.com",
    tipoMaterial: "Tuberías y plomería",
    tiempoEntrega: "48 horas",
    calificacion: 4.5,
    contacto: "Lic. Ana Sánchez",
  },
  {
    id: 3,
    nombre: "Electricidad Total",
    telefono: "555-345-6789",
    direccion: "Boulevard Electrón 789",
    correo: "servicio@electricidadtotal.com",
    tipoMaterial: "Material eléctrico",
    tiempoEntrega: "24 horas",
    calificacion: 4.9,
    contacto: "Ing. Carlos Ramírez",
  },
  {
    id: 4,
    nombre: "Ventanas y Cristales Seguros",
    telefono: "555-456-7890",
    direccion: "Av. Transparente 321",
    correo: "cotizaciones@cristalesseguros.com",
    tipoMaterial: "Vidrios y ventanas",
    tiempoEntrega: "3-5 días",
    calificacion: 4.7,
    contacto: "Arq. Lucía Fernández",
  },
  {
    id: 5,
    nombre: "Pisos de Lujo S.A.",
    telefono: "555-567-8901",
    direccion: "Calle Porcelanato 654",
    correo: "info@pisosdelujo.com",
    tipoMaterial: "Pisos y recubrimientos",
    tiempoEntrega: "5-7 días",
    calificacion: 4.6,
    contacto: "Diseñadora Mariana Gómez",
  },
  {
    id: 6,
    nombre: "Hierros y Estructuras Férreas",
    telefono: "555-678-9012",
    direccion: "Av. Metalúrgica 987",
    correo: "hierros@ferreas.com",
    tipoMaterial: "Estructuras metálicas",
    tiempoEntrega: "7-10 días",
    calificacion: 4.4,
    contacto: "Ing. Jorge Torres",
  },
  {
    id: 7,
    nombre: "Pinturas y Decoraciones ColorPlus",
    telefono: "555-789-0123",
    direccion: "Calle Pigmento 654",
    correo: "colorplus@decoraciones.com",
    tipoMaterial: "Pinturas y acabados",
    tiempoEntrega: "24 horas",
    calificacion: 4.8,
    contacto: "Diseñador Alejandro Ruiz",
  },
  {
    id: 8,
    nombre: "Sanitarios y Baños Elegantes",
    telefono: "555-890-1234",
    direccion: "Boulevard Sanitario 321",
    correo: "elegante@sanitarios.com",
    tipoMaterial: "Muebles para baño",
    tiempoEntrega: "3-5 días",
    calificacion: 4.3,
    contacto: "Lic. Patricia Castro",
  },
  {
    id: 9,
    nombre: "Techumbres y Cubiertas Resistentes",
    telefono: "555-901-2345",
    direccion: "Av. Techumbre 852",
    correo: "techos@resistentes.com",
    tipoMaterial: "Material para techos",
    tiempoEntrega: "5-7 días",
    calificacion: 4.7,
    contacto: "Ing. Fernando Mendoza",
  },
  {
    id: 10,
    nombre: "Jardinería y Paisajismo Natural",
    telefono: "555-012-3456",
    direccion: "Camino Verde 147",
    correo: "natural@jardineria.com",
    tipoMaterial: "Plantas y materiales para jardín",
    tiempoEntrega: "2-3 días",
    calificacion: 4.9,
    contacto: "Biólogo Luis Herrera",
  },
];
